### PR TITLE
Masala list

### PR DESCRIPTION
**Pull request by nicolas-zozol**

### CODE REVIEW

**Comment by d-plaindoux** [comment]
I do not understand the drastic modification of the List class?

**Comment by d-plaindoux** [comment]
If the problem is the `void` we must design a specific class for this purpose where the void is the neutral element (If I understand) of a pseudo tuple class. The confusion between this pseudo tuple and the list is not the best approach. I frankly prefer a clean separation of concern between the original monadic list and the missing tuple class which might be a monad (to be proven).

```
// Neutral element
(a0,...,an) + void = (a0,...,an)
void + (a0,...,an) = (a0,...,an)
// Append
(a0,...,an) + (b0,...,bm) = (a0,...,an,b0,...,bm)
// Associativity
((a0,...,an) + (b0,...,bm)) + (c0,...,cp) = (a0,...,an,b0,...,bm,c0,...,cp)
(a0,...,an) + ((b0,...,bm) + (c0,...,cp)) = (a0,...,an,b0,...,bm,c0,...,cp)
```

**Comment by d-plaindoux** [comment]
The simplest solution is: 
- rename list (no more list)
- remove the specific code with this `ugly` masala type.

**Comment by nicolas-zozol** [comment]
I've made a quick and dirty fix for List to test the `array()` and `single()` interface which I think is pretty cool. It was probably premature to put that in dev.
Totally ok to rename the List in Tuple() - I have already rewritten the code in a simpler way.

I have one question to be sure that we share the same idea. For now, there was a List/Tuple, Neutral and Element, which can be a number or an array. Do you consider any single Element like 'a' as a Tuple with one element ?

**Comment by nicolas-zozol** [comment]
I have a cleaner working concept (all tests passes)


```js
    then(p) {
        return this.flatMap(a =>
            p.map(b =>  new Tuple([]).append(a).append(b))
        );
    }


```

And for the Tuple

```js


class Tuple {

    constructor(array) {
        this.value = array;
    }

    array() {
        return [...this.value];
    }

    single() {
        return this.value[0];
    }

    join(j) {
        return this.value.join(j);
    }

    append(element) {
        if (element === NEUTRAL) {
            return new Tuple([...this.value]);
        }
        if (isTuple(element)) {
            return new Tuple([...this.value, ...element.value]);
        }
        // single element
        return new Tuple([...this.value, element]);
    }
}
```

**Pull request merged**
